- name: install xorg
  xbps:
    name: "{{item}}"
    state: latest
  loop:
    - xorg-minimal
    - xorg-server
    - xorg-fonts
    - xprop
    - xrdb
    - xrandr
    - xclipboard
    - xinit
    - xbacklight

- name: install fonts
  xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - font-fira-otf
    - font-fira-ttf
    - font-sourcecodepro
    - font-awesome

# not suitable for minimal
- name: configure home desktop
  xbps:
    name: "{{item}}"
    state: latest
  loop:
    - xf86-video-nouveau
  when: model == "home"

- name: configure VM
  xbps:
    name: "{{item}}"
    state: latest
  loop:
    - open-vm-tools
    - xf86-video-vmware
  when: model == "vm"
