- name: Install utilities
  xbps:
    name: "{{item}}"
    state: latest
  loop:
    - emacs-x11
    - vim
    - git
    - ranger
    - pass
    - openvpn
    - unzip
    - the_silver_searcher
    - curl
