[icons]
name = "awesome"
[theme]
name = "space-villain"

[[block]]
block = "nvidia_gpu"
interval = 10
show_memory = false
show_clocks = true

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "battery"
interval = 60
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
